services:
  - type: web
    name: tblinc-backend
    runtime: python
    rootDir: backend
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-hz97dq2vi3(*w_ghlfhe07d8c!)t^#idp+=e*&u0gbf()s^+-s
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
      # Contabo API
      - key: CONTABO_CLIENT_ID
        value: INT-14498746
      - key: CONTABO_CLIENT_SECRET
        value: ge0nQpTMDfZYnGatHEeQSk7dZ0hlpjxU
      - key: CONTABO_API_USER
        value: tblinc810@gmail.com
      - key: CONTABO_API_PASSWORD
        value: "Aaaa1111@@a"
      # Email (SMTP)
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        value: tblinc810@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: rteohhxmyoydwjix
      - key: DEFAULT_FROM_EMAIL
        value: "TBLINC <no-reply@tblinc.com>"
      # Currency API
      - key: CURRENCY_API_KEY
        value: fca_live_36um3nfiCgxWh8yz6mk70OsfR8u6h707OX0OXKK0
      # SSLCommerz
      - key: SSL_STORE_ID
        value: tblin663e2646399c5
      - key: SSL_STORE_PASS
        value: tblin663e2646399c5@ssl
      - key: SSL_IS_SANDBOX
        value: "True"
      # PayPal
      - key: PAYPAL_CLIENT_ID
        value: AQ_your_paypal_client_id_here
      - key: PAYPAL_SECRET
        value: EB_your_paypal_secret_here
      - key: PAYPAL_MODE
        value: sandbox
      # SMS
      - key: SMS_API_KEY
        value: your_sms_api_key_here
      - key: SMS_SENDER_ID
        value: TBLINC
      - key: SMS_API_URL
        value: https://msg.elitbuzz-bd.com/smsapi
