# Generated by Django 6.0.5 on 2026-05-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblinc', '0008_systemsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualpaymentrequest',
            name='note',
        ),
        migrations.AddField(
            model_name='manualpaymentrequest',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='manualpaymentrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='manualpaymentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='SUCCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('PURCHASE', 'Purchase'), ('SPEND', 'Spend')], max_length=20),
        ),
    ]
