# Generated by Django 6.0.5 on 2026-05-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblinc', '0010_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
