# Generated by Django 6.0.5 on 2026-05-13 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblinc', '0012_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
