# Generated by Django 6.0.5 on 2026-05-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblinc', '0017_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpaymentrequest',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
