# Generated by Django 6.0.5 on 2026-05-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblinc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan_id',
            field=models.CharField(default='vps-s', max_length=50),
        ),
    ]
