# Generated by Django 6.0.5 on 2026-05-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblinc', '0013_user_is_reseller_user_parent_reseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='markup_amount',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
        ),
    ]
