# Generated by Django 6.0.5 on 2026-05-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblinc', '0014_user_markup_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='server',
            name='renewal_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
